# YOLOv6 🚀 by YOLOAir, GPL-3.0 license
# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple no
anchors: 1  # number of anchors

# YOLOv6 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, RepVGGBlockv6, [64, 3, 2]],
   [-1, 1, RepVGGBlockv6, [128, 3, 2]],
   [-1, 6, RepBlock   , [64, 64]],     # 2
   [-1, 1, RepVGGBlockv6, [256, 3, 2]],
   [-1, 12, RepBlock   , [128, 128]],   # 4
   [-1, 1, RepVGGBlockv6, [512, 3, 2] ],
   [-1, 18, RepBlock   , [256, 256] ],  # 6
   [-1, 1, RepVGGBlockv6, [1024, 3, 2] ],
   [-1, 6, RepBlock   , [512, 512] ],  # 8
   [-1, 1, SimSPPF    , [512, 512, 5]],   # 9
  ]

# YOLOv6 head
head:
  [[-1, 1, SimConv, [512, 128, 1, 1]],  # 10
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],           #cat
   [-1, 12, RepBlock, [384, 128]],    # 13

   [-1, 1, SimConv, [128, 64, 1, 1]],   # 14
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],           #cat
   [-1, 12, RepBlock, [192, 64]],     # 17 / [64, 80, 80] P3

   [-1, 1, SimConv, [64, 64, 3, 2]],    # 18
   [[-1, 14], 1, Concat, [1]],          # 19
   [-1, 12, RepBlock, [128, 128]],     # 20 / [128, 40, 40] P4

   [-1, 1, SimConv, [128, 128, 3, 2]],   # 21
   [[-1, 10], 1, Concat, [1]],          # 22
   [-1, 12, RepBlock, [256, 256]],    # 23 / [256, 20, 20] P5
   [[17, 20, 23], 1, Detectv6, [nc, [64, 128, 256]]],  # Detect(P3, P4, P5)
  ]
